### ISSUE TITLE
api question

### ISSUE THREAD

**Issue by bchr02** [jarradseers/consign#2]
@jarradseers Great repo! 

Question though, what if instead of wanting to structure an express app like this:

```
\root
    \models
    \views
    \routers
    \public
```

I wanted to do something more modular like this:

```
\root
    \public
    \apps
        \app_one
            \models
            \views
            \routers
            \public
        \app_two
            \models
            \views
            \routers
            \public
```

Can your api handle this? If so how? Thanks.

**Comment by jarradseers** [comment]
Cheers for that :) yeah, there are a couple of ways depending on what you are after:

```js
consign({cwd: 'apps'});
```

This will include both apps in the one structure, otherwise you can run multiple instances of consign.

```js
consign({cwd: 'apps/app_one'}).into(app1);
consign({cwd: 'apps/app_two'}).into(app2);
```

Let me know if you need more information :) cheers.

**Comment by bchr02** [comment]
You're awesome! Thank you, I will give it a try.
