### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by aretw0** [jarradseers/consign#26]
Now i have this:

`consign({"cwd":process.cwd() + "\\app\\v1","verbose":false}).include("models").then("controllers").then("routes").into(app)
`

with

![image](https://user-images.githubusercontent.com/14055273/67768443-4802df00-fa31-11e9-99ae-b4a6ae3b6003.png)

In the future how can i accomplish api versioning versioning (v1/ v2/ routes)?

**Comment by Igor-Lopes** [comment]
I just use app/controllers/v1 or app/controllers/v2 in my project structure. Your consign setup should be able to load all directories just fine.
