### ISSUE TITLE
Question about recursive routes

### ISSUE THREAD

**Issue by udayms** [jarradseers/consign#5]
Hi... I have been trying to use consign in one of my projects. I am wondering if consign can consider folders as route paths... What I mean is - if I have some routes in file routes/user.js ... the generated routes are:
app.get('/user/', get_all);
app.get('/user/:id', get_all);
app.post('/user/:id', update);
app.post('/user', create);
app.detete('/user/:id' : del);

and all I do is just move the routes/user.js to routes/api/user.js ... now I want the routes to be generated routes to be:

app.get('/api/user/', get_all);
app.get('/api/user/:id', get_all);
app.post('/api/user/:id', update);
app.post('/api/user', create);
app.detete('/api/user/:id' : del);

Note that I have not made changes to the user.js file. Because now its in a subfolder, the subfolder gets added to the route path. Can Consign do something like this?

**Comment by jarradseers** [comment]
I'm sorry id need more specifics to understand what you are trying to achieve, consider the examples in the examples folder for the usage
