### ISSUE TITLE
custom name for a folder being consigned

### ISSUE THREAD

**Issue by lookageek** [jarradseers/consign#6]
Hi,

I have a folder `query_modules`, which i will consign to `app` like so.

```
\query_modules
   firstModule.js
   secondModule.js
```

```
consign().include('query_modules').into(app)
```

Now to access any of the modules inside `query_modules` I should ideally do

```
app.query_modules.firstModule
```

But this does not really bid well with JS naming convention which is `camelCase`

So, is there a way in consign to customize the name for the folder when consigning to make all modules in `query_modules` to be access like this?

```
app.queryModules.firstModule
```

**Comment by jarradseers** [comment]
Hi, not right now but i'll keep this in mind as a feature for the next version, thanks
